### ISSUE TITLE
Make seeder in model

### ISSUE THREAD

**Issue by jobstoit** [jobstoit/gqb#7]
Make a database seeder in the model.
The configuration markdown will have to look like this:
```yaml
seeds:
  user:
    fields: firstname, lastname, role
    values:
    - Job, Stoit, ADMIN
    - Dwane, Jonson, CUSTOMER
```
